# -*- coding: utf-8 -*-
"""Cópia de Modelo base

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11dFP9rRqkDyzqu1qMr_r5Rd6ui4-yk6k
"""

import math

def calcularTamanho(X,Y,Z):
  result = math.sqrt(X**2 + Y**2 + Z**2)
  return result

def calcularTamanho2(X2,Y2,Z2):
  result = math.sqrt(X2**2 + Y2**2 + Z2**2)
  return result

while True:
  print("1- Definir X Y Z") # Calcular o tamanho do vetor;
  print("2- ") # Normalizar o vetor, apresentando o vetor resultante da normalização;
  print("3- ") # Adicionar outro vetor ao que foi lido anteriormente, lendo os valores x, y e z deste novo vetor;
  print("4- ") # Subtrair outro vetor ao que foi lido anteriormente, lendo os valores x, y e z deste novo vetor;
  print("5- ") # Ler o valor de um escalar e realizar a multiplicação do mesmo pelo vetor, mostrando o vetor resultante;
  print("6- ") # Ler o valor de um escalar e realizar a divisão do mesmo pelo vetor, mostrando o vetor resultante;
  print("7- ") # Calcular o produto escalar do vetor lido anteriormente por outro vetor, lendo os valores x, y e z deste novo vetor e mostrando o resultado na tela.
  print("8- Terminar") # Terminar a execuçao

  op = int(input("Escolha uma opcao: "))
  print(" ")

  if op == 1:
    print("Definir: ")
    X = int(input("X: "))
    Y = int(input("Y: "))
    Z = int(input("Z: "))
    print(" ")

  elif op == 2:
    X = X / calcularTamanho(X,Y,Z)
    Y = Y / calcularTamanho(X,Y,Z)
    Z = Z / calcularTamanho(X,Y,Z)

    print("Valores normalizados: ")
    print("X: ", X)
    print("Y: ", Y)
    print("Z: ", Z)
    print(" ")

  elif op == 3:
    print("Definir: ")
    X2 = int(input("X2: "))
    Y2 = int(input("Y2: "))
    Z2 = int(input("Z2: "))
    print(" ")

    rX = X + X2
    rY = Y + Y2
    rZ = Z + Z2
    print("Valores somados: ")
    print("X: ", rX)
    print("Y: ", rY)
    print("Z: ", rZ)
    print(" ")

  elif op == 4:
    print("Definir: ")
    X2 = int(input("X2: "))
    Y2 = int(input("Y2: "))
    Z2 = int(input("Z2: "))
    print(" ")

    rX = X - X2
    rY = Y - Y2
    rZ = Z - Z2
    print("Valores subtraidos: ")
    print("X: ", rX)
    print("Y: ", rY)
    print("Z: ", rZ)
    print(" ")

  elif op == 5:
    print("Definir: ")
    X2 = int(input("X2: "))
    Y2 = int(input("Y2: "))
    Z2 = int(input("Z2: "))
    print(" ")

    rX = X * X2
    rY = Y * Y2
    rZ = Z * Z2
    print("Valores multiplicados: ")
    print("X: ", rX)
    print("Y: ", rY)
    print("Z: ", rZ)
    print(" ")

  elif op == 6:
    print("Definir: ")
    X2 = int(input("X2: "))
    Y2 = int(input("Y2: "))
    Z2 = int(input("Z2: "))
    print(" ")

    rX = X / X2
    rY = Y / Y2
    rZ = Z / Z2
    print("Valores somados: ")
    print("X: ", rX)
    print("Y: ", rY)
    print("Z: ", rZ)
    print(" ")

  elif op == 7:
    print("Definir: ")
    X2 = int(input("X2: "))
    Y2 = int(input("Y2: "))
    Z2 = int(input("Z2: "))
    print(" ")

    resultado = (X * X2) + (Y * Y2) + (Z * Z2)

    print("Valores somados: ")
    print("Resultado: ", resultado)
    print(" ")

  elif op == 8:
    print("Adios")
    break

  else:
    print("Opcao invalida")
    print(" ")